auto: true
server: true
server_port: 3000
pygments: false
lsi: false

source: ./web
plugins: ./web/_plugins

url: http://movelang.org

permalink: /:year/:month/:day/:title.html
#paginate: 10
markdown: rdiscount
#markdown: kramdown
# enables SmartyPants (nice curly quotation marks, em/en dashes, elipses, etc):
rdiscount:
  extensions: [smart]
  generate_toc: true

kramdown:
  auto_ids: true
